# Generated by Django 2.2.7 on 2019-11-13 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_state', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=5, null=True)),
                ('date', models.DateTimeField(verbose_name='sale date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_dashboard.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(max_length=200)),
                ('prop_code', models.IntegerField(default=0)),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_dashboard.Region')),
            ],
        ),
    ]
