# Generated by Django 2.2.7 on 2019-11-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='prop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_dashboard.Property'),
        ),
    ]
