# Generated by Django 2.2.7 on 2019-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_dashboard', '0002_auto_20191113_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(verbose_name='Sale Date'),
        ),
    ]
