# Generated by Django 2.2.7 on 2019-11-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_dashboard', '0004_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_code',
            field=models.IntegerField(default=0, verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_dashboard.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
    ]
