# Generated by Django 2.2.7 on 2019-11-15 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_dashboard', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prop_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_dashboard.Property')),
                ('prop_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_dashboard.Sale')),
            ],
        ),
    ]
