# Generated by Django 2.2.7 on 2019-11-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_dashboard', '0007_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_dashboard.Person', verbose_name='Person'),
        ),
    ]
